### ISSUE TITLE
Plugin gives error Warning: Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.

### ISSUE THREAD

**Issue by kam15** [transistorsoft/cordova-plugin-background-fetch#10]
I installed this background fetch plugin using CLI. Then I placed the sample code as given in the readme in the DeviceReady function. 
On running the app,I don't see "CDVBackgroundFetch configure" in the logs. If I simulate a background fetch on the simulator, I get the error: - 

CDVBackgroundFetch onFetch 
Warning: Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called. 

Where am I going wrong? I haven't made any changes to the code except adding the sample code to call Fetcher.configure in onDeviceReady. Any help will be GREATLY appreciated. Thanks in advance!

**Comment by nokai** [comment]
I do not work for me. Have a simple example to see it?

**Comment by mnadler** [comment]
Hi there, has this issue been resolved?  I am including the appropriate js file and building with Phonegapbuild.  Thanks!

**Comment by HAZARDU5** [comment]
I'm having the same issue with Cordova on iOS 9.0.1. Works when triggering the fetch via `Debug -> Simulate Background Fetch` in XCode on an actual device, however won't work if I create a new Scheme in XCode and run the app on the device with `Launch due to a background fetch event` selected (forces the app to open as if it had launched due to a background fetch event).

This was previously working correctly on iOS 8.3.

**Comment by Mojo90** [comment]
Same thing for me. It does not appear all the time only sometimes but even if I comment out the mentioned 3 lines.


Another thing: 

How do you debug code after termination? Because I implemented katzers local notification plugin to fire everytime a local push as the ```fetchCallback = function()``` or ```failureCallback = function()``` gets called. But it does not work anytime App is in Background, sometimes yes sometimes no.

If I close the App (termination - stopOnTerminate is set to false of course) then no single Local Notification is fired --> I assume it completely stops working (for me) if App is closed. Thus my question how do you debug after termination of App?

**Comment by Pixelartdev** [comment]
The solutions provided here didn't solved in my case. I also found out that it only happens on real devices, the simulator has no problem with the code (in my case, in your case it could be different)

**Comment by youurayy** [comment]
The fix by HAZARDU5 fixes it for me.

@christocracy do you plan on integrating this and (re-)publishing into NPM / Cordova?

**Comment by christocracy** [comment]
I haven't really been touching this lib in a looong time.

**Comment by christocracy** [comment]
[This guy](https://www.npmjs.com/package/cordova-plugin-fork-pebblecode-background-fetch) is doing something with it.
