### ISSUE TITLE
Adding plugin fails asking for cordova-android 7.0.0

### ISSUE THREAD

**Issue by filippopossenti** [transistorsoft/cordova-plugin-background-fetch#91]
Hi,

apparently I can't add the plugin anymore to our projects, for any version I tried.

I tried:
cordova plugin add cordova-plugin-background-fetch@5.3.0
cordova plugin add cordova-plugin-background-fetch@5.2.1
cordova plugin add cordova-plugin-background-fetch@5.4.0

The error is always the same:
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0
Skipping 'cordova-plugin-background-fetch' for android

npm -v
6.0.1

The OS is MacOS Sierra.

Can you advise?

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

  Provide a general summary of the issue in the Title above 
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
<!-- include iOS / Android logs
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat

**Comment by filippopossenti** [comment]
Plugin won't install.

Your Environment
Plugin version: Any. Verified on 5.2.1, 5.3.0, 5.4.0
Platform: Android
OS version: Any supported by cordova-android@6.3.0
Device manufacturer / model: Any
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): cordova-android@6.3.0
Plugin config: not applicable
Expected Behavior

Should install.

Actual Behavior

It complains that I don't have cordova-android@7.0.0
Steps to Reproduce

Uninstall the plugin from your project. Install it again.

Context

Debug logs

**Comment by christocracy** [comment]
```
ford-2:Cordova8 chris$ cordova -v
8.0.0

ford-2:Cordova8 chris$ cordova platform
Installed platforms:
  android 6.3.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

ford-2:Cordova8 chris$ cordova plugin add cordova-plugin-background-fetch@5.3.0

Installing "cordova-plugin-background-fetch" for android
Subproject Path: CordovaLib
Adding cordova-plugin-background-fetch to package.json
Saved plugin info for "cordova-plugin-background-fetch" to config.xml
ford-2:Cordova8 chris$
ford-2:Cordova8 chris$ cordova plugins
cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"
.
.
.
ford-2:Cordova8 chris$
ford-2:Cordova8 chris$
```

**Comment by christocracy** [comment]
I'm sure these are cordova / ionic issues.

After removing `cordova-background-geolocation` (and all its dependencies, including `background-fetch`, observe your `plugin.xml`, `package.json`, `plugin/fetch.json` for references to these plugins.  Delete all references.

```
$ cordova platform remove android
$ cordova platform remove ios
$ rm -rf node_modules
$ npm install
```

Now start from a clean slate.
