### ISSUE TITLE
[support] where i put my custom function

### ISSUE THREAD

**Issue by Mathe13** [transistorsoft/cordova-plugin-background-fetch#94]
I'm having problems with one of your ionic plugins (cordova-plugin-background-fetch
) I need to run a web request and a push every n minutes but your plugin just runs the trigger from my ts file, can you help me? where should I call my function?

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
